name: PageSpeed metrics

on:
  schedule:
    - cron: "0 6 * * 1" # Mondays 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
      - name: Psicología Landing PageSpeed report
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: NOT_NEEDED
          base: ""
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://psicologialanding.netlify.app
